# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_InformasiBarang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformasiBarang(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(460, 237)
        dialog.setStyleSheet("#background {\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"#kode_label,\n"
"#nama_label,\n"
"#kuantiti_label,\n"
"#lokasi_label {\n"
"    color: rgb(30, 30, 30);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#kode_info,\n"
"#nama_info,\n"
"#kuantiti_info,\n"
"#lokasi_info {\n"
"    padding: 4px 8px;\n"
"    font-size: 14px;\n"
"    color: rgb(30, 30, 30);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"#edit_btn {\n"
"    padding: 5px 0;\n"
"    font-size: 14px;\n"
"    color: rgb(88, 0, 169);\n"
"    background-color: transparent;\n"
"    border: 1px solid  rgb(88, 0, 169);\n"
"}\n"
"\n"
"#edit_btn:hover {\n"
"    background-color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"#hapus_btn {\n"
"    padding: 5px 0;\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(156, 0, 0);\n"
"    border: 1px solid  rgb(156, 0, 0);\n"
"}\n"
"\n"
"#hapus_btn:hover {\n"
"    background-color: rgb(120, 0, 0);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.background = QtWidgets.QWidget(dialog)
        self.background.setObjectName("background")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.background)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setContentsMargins(24, 24, 24, 24)
        self.layout.setSpacing(24)
        self.layout.setObjectName("layout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.kuantiti_info = QtWidgets.QLabel(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kuantiti_info.sizePolicy().hasHeightForWidth())
        self.kuantiti_info.setSizePolicy(sizePolicy)
        self.kuantiti_info.setMinimumSize(QtCore.QSize(300, 0))
        self.kuantiti_info.setMaximumSize(QtCore.QSize(300, 16777215))
        self.kuantiti_info.setText("")
        self.kuantiti_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.kuantiti_info.setWordWrap(True)
        self.kuantiti_info.setObjectName("kuantiti_info")
        self.gridLayout.addWidget(self.kuantiti_info, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 2)
        self.lokasi_label = QtWidgets.QLabel(self.background)
        self.lokasi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lokasi_label.setObjectName("lokasi_label")
        self.gridLayout.addWidget(self.lokasi_label, 3, 0, 1, 1)
        self.kuantiti_label = QtWidgets.QLabel(self.background)
        self.kuantiti_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kuantiti_label.setObjectName("kuantiti_label")
        self.gridLayout.addWidget(self.kuantiti_label, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 2)
        self.kode_info = QtWidgets.QLabel(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.kode_info.sizePolicy().hasHeightForWidth())
        self.kode_info.setSizePolicy(sizePolicy)
        self.kode_info.setMinimumSize(QtCore.QSize(300, 0))
        self.kode_info.setMaximumSize(QtCore.QSize(300, 16777215))
        self.kode_info.setText("")
        self.kode_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.kode_info.setWordWrap(True)
        self.kode_info.setObjectName("kode_info")
        self.gridLayout.addWidget(self.kode_info, 0, 3, 1, 1)
        self.nama_label = QtWidgets.QLabel(self.background)
        self.nama_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nama_label.setObjectName("nama_label")
        self.gridLayout.addWidget(self.nama_label, 1, 0, 1, 1)
        self.lokasi_info = QtWidgets.QLabel(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lokasi_info.sizePolicy().hasHeightForWidth())
        self.lokasi_info.setSizePolicy(sizePolicy)
        self.lokasi_info.setMinimumSize(QtCore.QSize(300, 0))
        self.lokasi_info.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lokasi_info.setText("")
        self.lokasi_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lokasi_info.setWordWrap(True)
        self.lokasi_info.setObjectName("lokasi_info")
        self.gridLayout.addWidget(self.lokasi_info, 3, 3, 1, 1)
        self.kode_label = QtWidgets.QLabel(self.background)
        self.kode_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kode_label.setObjectName("kode_label")
        self.gridLayout.addWidget(self.kode_label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 2)
        self.nama_info = QtWidgets.QLabel(self.background)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.nama_info.sizePolicy().hasHeightForWidth())
        self.nama_info.setSizePolicy(sizePolicy)
        self.nama_info.setMinimumSize(QtCore.QSize(300, 0))
        self.nama_info.setMaximumSize(QtCore.QSize(300, 16777215))
        self.nama_info.setText("")
        self.nama_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.nama_info.setWordWrap(True)
        self.nama_info.setObjectName("nama_info")
        self.gridLayout.addWidget(self.nama_info, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 2)
        self.layout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.edit_btn = QtWidgets.QPushButton(self.background)
        self.edit_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.edit_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout_2.addWidget(self.edit_btn)
        self.hapus_btn = QtWidgets.QPushButton(self.background)
        self.hapus_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.hapus_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.hapus_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hapus_btn.setObjectName("hapus_btn")
        self.horizontalLayout_2.addWidget(self.hapus_btn)
        self.layout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.layout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.background, 1, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Informasi Barang"))
        self.lokasi_label.setText(_translate("dialog", "Lokasi"))
        self.kuantiti_label.setText(_translate("dialog", "Kuantiti"))
        self.nama_label.setText(_translate("dialog", "Nama barang"))
        self.kode_label.setText(_translate("dialog", "Kode barang"))
        self.edit_btn.setText(_translate("dialog", "Edit"))
        self.hapus_btn.setText(_translate("dialog", "Hapus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_InformasiBarang()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
