# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_KonfirmasiHapus.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KonfirmasiHapus(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(435, 168)
        dialog.setStyleSheet("#background {\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"#title {\n"
"    color: rgb(30, 30, 30);\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#text {\n"
"    color: rgb(30, 30, 30);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#batal_btn {\n"
"    padding: 5px 0;\n"
"    font-size: 14px;\n"
"    color: rgb(156, 0, 0);\n"
"    background-color: transparent;\n"
"    border: 1px solid  rgb(156, 0, 0);\n"
"}\n"
"\n"
"#batal_btn:hover {\n"
"    background-color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"#hapus_btn {\n"
"    padding: 5px 0;\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(156, 0, 0);\n"
"    border: 1px solid  rgb(156, 0, 0);\n"
"}\n"
"\n"
"#hapus_btn:hover {\n"
"    background-color: rgb(120, 0, 0);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.background = QtWidgets.QWidget(dialog)
        self.background.setObjectName("background")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.background)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setContentsMargins(24, 24, 24, 24)
        self.layout.setSpacing(24)
        self.layout.setObjectName("layout")
        self.title = QtWidgets.QLabel(self.background)
        self.title.setObjectName("title")
        self.layout.addWidget(self.title)
        self.text = QtWidgets.QLabel(self.background)
        self.text.setObjectName("text")
        self.layout.addWidget(self.text)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.batal_btn = QtWidgets.QPushButton(self.background)
        self.batal_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.batal_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.batal_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.batal_btn.setObjectName("batal_btn")
        self.horizontalLayout_2.addWidget(self.batal_btn)
        self.hapus_btn = QtWidgets.QPushButton(self.background)
        self.hapus_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.hapus_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.hapus_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hapus_btn.setObjectName("hapus_btn")
        self.horizontalLayout_2.addWidget(self.hapus_btn)
        self.layout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.layout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.background, 1, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Konfirmasi Penghapusan"))
        self.title.setText(_translate("dialog", "Hapus Barang ?"))
        self.text.setText(_translate("dialog", "Barang yang telah dihapus tidak dapat dikembalikan"))
        self.batal_btn.setText(_translate("dialog", "Batal"))
        self.hapus_btn.setText(_translate("dialog", "Hapus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_KonfirmasiHapus()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
