# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_TambahBarang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TambahBarang(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(460, 245)
        dialog.setStyleSheet("#background {\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"#kode_label,\n"
"#nama_label,\n"
"#kuantiti_label,\n"
"#lokasi_label {\n"
"    color: rgb(30, 30, 30);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#nama_mandatory {\n"
"    color: rgb(156, 0, 0);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#kode_input,\n"
"#nama_input,\n"
"#kuantiti_input,\n"
"#lokasi_input {\n"
"    padding: 4px 8px;\n"
"    font-size: 14px;\n"
"    color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"#kode_input:hover,\n"
"#nama_input:hover,\n"
"#kuantiti_input:hover,\n"
"#lokasi_input:hover {\n"
"    border: 1px solid rgb(73, 0, 131);\n"
"}\n"
"\n"
"#kode_input:focus,\n"
"#nama_input:focus,\n"
"#kuantiti_input:focus,\n"
"#lokasi_input:focus {\n"
"    border: 1px solid rgb(133, 0, 237);\n"
"}\n"
"\n"
"#batal_btn {\n"
"    padding: 5px 0;\n"
"    font-size: 14px;\n"
"    color: rgb(88, 0, 169);\n"
"    background-color: transparent;\n"
"    border: 1px solid  rgb(88, 0, 169);\n"
"}\n"
"\n"
"#batal_btn:hover {\n"
"    background-color: rgb(215, 215, 215);\n"
"}\n"
"\n"
"#simpan_btn {\n"
"    padding: 5px 0;\n"
"    font-size: 14px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(88, 0, 169);\n"
"    border: 1px solid  rgb(88, 0, 169);\n"
"}\n"
"\n"
"#simpan_btn:hover {\n"
"    background-color: rgb(69, 0, 133);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.background = QtWidgets.QWidget(dialog)
        self.background.setObjectName("background")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.background)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setContentsMargins(24, 24, 24, 24)
        self.layout.setSpacing(24)
        self.layout.setObjectName("layout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.nama_mandatory = QtWidgets.QLabel(self.background)
        self.nama_mandatory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.nama_mandatory.setObjectName("nama_mandatory")
        self.gridLayout.addWidget(self.nama_mandatory, 1, 1, 1, 1)
        self.kuantiti_label = QtWidgets.QLabel(self.background)
        self.kuantiti_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kuantiti_label.setObjectName("kuantiti_label")
        self.gridLayout.addWidget(self.kuantiti_label, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        self.lokasi_input = QtWidgets.QLineEdit(self.background)
        self.lokasi_input.setMinimumSize(QtCore.QSize(300, 0))
        self.lokasi_input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lokasi_input.setMaxLength(100)
        self.lokasi_input.setObjectName("lokasi_input")
        self.gridLayout.addWidget(self.lokasi_input, 5, 3, 1, 1)
        self.lokasi_label = QtWidgets.QLabel(self.background)
        self.lokasi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lokasi_label.setObjectName("lokasi_label")
        self.gridLayout.addWidget(self.lokasi_label, 5, 0, 1, 1)
        self.kode_input = QtWidgets.QLineEdit(self.background)
        self.kode_input.setMinimumSize(QtCore.QSize(300, 0))
        self.kode_input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.kode_input.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.kode_input.setMaxLength(30)
        self.kode_input.setObjectName("kode_input")
        self.gridLayout.addWidget(self.kode_input, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.nama_label = QtWidgets.QLabel(self.background)
        self.nama_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nama_label.setObjectName("nama_label")
        self.gridLayout.addWidget(self.nama_label, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(8, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.nama_input = QtWidgets.QLineEdit(self.background)
        self.nama_input.setMinimumSize(QtCore.QSize(300, 0))
        self.nama_input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.nama_input.setMaxLength(50)
        self.nama_input.setObjectName("nama_input")
        self.gridLayout.addWidget(self.nama_input, 1, 3, 1, 1)
        self.kode_label = QtWidgets.QLabel(self.background)
        self.kode_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kode_label.setObjectName("kode_label")
        self.gridLayout.addWidget(self.kode_label, 0, 0, 1, 1)
        self.kuantiti_input = QtWidgets.QLineEdit(self.background)
        self.kuantiti_input.setMinimumSize(QtCore.QSize(300, 0))
        self.kuantiti_input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.kuantiti_input.setObjectName("kuantiti_input")
        self.gridLayout.addWidget(self.kuantiti_input, 3, 3, 1, 1)
        self.layout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.batal_btn = QtWidgets.QPushButton(self.background)
        self.batal_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.batal_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.batal_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.batal_btn.setObjectName("batal_btn")
        self.horizontalLayout_2.addWidget(self.batal_btn)
        self.simpan_btn = QtWidgets.QPushButton(self.background)
        self.simpan_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.simpan_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.simpan_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.simpan_btn.setObjectName("simpan_btn")
        self.horizontalLayout_2.addWidget(self.simpan_btn)
        self.layout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.layout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.background, 1, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Tambah Barang"))
        self.nama_mandatory.setText(_translate("dialog", "*"))
        self.kuantiti_label.setText(_translate("dialog", "Kuantiti"))
        self.lokasi_label.setText(_translate("dialog", "Lokasi"))
        self.nama_label.setText(_translate("dialog", "Nama barang"))
        self.kode_label.setText(_translate("dialog", "Kode barang"))
        self.batal_btn.setText(_translate("dialog", "Batal"))
        self.simpan_btn.setText(_translate("dialog", "Simpan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_TambahBarang()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
